---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgAkSOYdHjPb45Ihswez/ztWgNdHRN/5eDQOE6BpmvC+NdXPazsH/kTr2nuvqFsBFxleNujKRl/YBsqkXPUNDqXvqRYJ+TtHUkyU+r1H6tSQMnYiEoY9b/VLebKdBl8h1PCuDKiZXC6DzlI5d6U+5hC1O2AstxrKGado9l+BI8lb8ebmqWmLywU65uwnLH1783C/ylkPJX29nG1Wzf+CDH9RaDAqspwe1u8/wQpR/Ohm6Tsi7KPxljq2eXajoVvip/fg+vFQ5bL5+KGHb4cu7TaXagUQcSKutz0U5VWlCS1isQOZmujvMm9yCJ5H7xU1dsf8eOs6Fk9WFua/+LGh3F/o5Yt4pAng9x53aPNBMiOs3VWsbAP7kHJihZaHWw0B7o+hTg6ZlRTShGm/4Yv8IhpLx1mixAXC1WTz+quAqFUIKWdfwUsvv8aI/41A9dsbB1ceal2J+r+j3eS9iCMwaze18vRAPHxjACNMo6GgyHwZNVAweAUQ1oam5uFgMeKOzuiS3OWM4zBRBbtROilFsAjINUzffWAMnJ+pyx6S+Q2Qi79yI1X7eMun4eCRGH4iCq1brbp/jO7+0OShuRHuTs5GgIDPxglZgx4CpJS8DCjnRBDSLJ9uZ85nYRX1f7oFrQC8ZAc+FsTDksGQEcEX0RrJuuKJYFr2Yka1I1XDohpR+5nYx7grtl5FMskVEIZ5k/VCU4YMPZaqvoaOQOkn7dpIMye4l72FmSIFG2dt+H6H78B+1Gu1v/ivZeQDicBrwvMKBQ==
  template:
    metadata:
      name: api-keys
      namespace: default
    type: Opaque
